sonar.projectKey=Complaint-Ticket-Management-System
sonar.projectName=Complaint Ticket Management System
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=vendor/**, tests/**
sonar.language=php
sonar.sourceEncoding=UTF-8
