sonar.projectKey=complaint-ticket-management-system
sonar.projectName=Complaint Ticket Management System
sonar.projectVersion=1.0

# Path to source code
sonar.sources=.
sonar.exclusions=vendor/**, tests/**

# Source language and encoding
sonar.language=php
sonar.sourceEncoding=UTF-8
